[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Arsip"
  url = "archive"
  weight = 3

[[main]]
  identifier = "posts"
  name = "Artikel"
  url = "posts"
  weight = 4



[[main]]
  idenifier = "Topik"
  name = "Topik"
  url = "#"
  weight = 5
    
[[main]]
  parent = "Topik"
  name = "Perkantoran"
  url = "perkantoran"

[[main]]
  parent = "Topik"
  name = "Tips"
  url = "/"



